"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x4z@k&&(agitg#-oxm-%i8+9d_v1-8!34un-g=6lxql0)j(i71'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = "bookshelf.CustomUser"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'relationship_app',
    'csp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware'
]

CSP_DEFAULT_SRC = ("'self'",)

# Browser security
SECURE_BROWSER_XSS_FILTER = True          # Protects against reflected XSS
X_FRAME_OPTIONS = "DENY"                  # Prevents clickjacking (site can't be embedded in <iframe>)
SECURE_CONTENT_TYPE_NOSNIFF = True        # Stops browsers from guessing MIME type

# Cookies security (should be True in production with HTTPS)
CSRF_COOKIE_SECURE = True                 # CSRF cookie only sent over HTTPS
SESSION_COOKIE_SECURE = True              # Session cookie only sent over HTTPS


# Redirect all non-HTTPS requests to HTTPS.
# IMPORTANT: In development (localhost) you may want this False. Keep True in production.
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS)
# Tells browsers to only use HTTPS for this site for the given number of seconds.
# 31536000 = 1 year. Only enable long periods after you confirm HTTPS works.
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # include subdomains in HSTS
SECURE_HSTS_PRELOAD = True            # allow site to be added to browser preload lists

# Cookies: only send cookies (session/csrf) over HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Browser hardening headers
X_FRAME_OPTIONS = "DENY"              # prevents clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True    # prevents MIME sniffing
SECURE_BROWSER_XSS_FILTER = True      # enables XSS filter in browsers (deprecated in some browsers, but harmless)

# If your Django site is behind a reverse proxy/load balancer (common in production),
# the proxy typically sets X-Forwarded-Proto header. Tell Django which header to trust:
# (e.g., when using nginx proxy_pass with proxy_set_header X-Forwarded-Proto $scheme;)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# If you serve on a domain and want CSRF to accept absolute origins:
# Replace example.com with your real domain(s). Use https://... entries.
# NOTE: Django >= 4.0 requires scheme in entries.
CSRF_TRUSTED_ORIGINS = [
    "https://yourdomain.com",
    "https://www.yourdomain.com",
]

# Content Security Policy (optional) — recommended to restrict sources.
# If you installed django-csp, configure CSP via settings (see docs). Example:
# CSP_DEFAULT_SRC = ("'self'",)
# CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com")
# CSP_SCRIPT_SRC = ("'self'", "https://cdnjs.cloudflare.com")
#
# If you are not using django-csp, you can set headers manually in middleware or responses.


ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


INSTALLED_APPS += ["csp"]

MIDDLEWARE += [
    "csp.middleware.CSPMiddleware",
]

CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com")
CSP_SCRIPT_SRC = ("'self'", "https://cdnjs.cloudflare.com")  # if you load scripts
